# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: Grygorii Tertychnyi

BBPATH =. "${LAYERDIR}:"
BBFILES += " \
  ${LAYERDIR}/recipes-*/*/*.bb \
  ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "butterfly"
BBFILE_PATTERN_butterfly = "^${LAYERDIR}/"

# the priority for recipes from this layer must be higher than any
# recipes from opensource layers
BBFILE_PRIORITY_butterfly = "27"

LAYERVERSION_butterfly = "1"

LAYERDEPENDS_butterfly = "core"
# meta-oe
LAYERDEPENDS_butterfly += "openembedded-layer"
# meta-networking
LAYERDEPENDS_butterfly += "networking-layer"
# meta-python
LAYERDEPENDS_butterfly += "meta-python"
# meta-perl
LAYERDEPENDS_butterfly += "perl-layer"

LAYERSERIES_COMPAT_butterfly = "scarthgap"
